project:
  type: book
  output-dir: docs
execute: 
  cache: true
  freeze: false
  echo: false
  eval: true
bibliography: MATH80667A.bib
highlight: tango
split_bib: no
title-block-style: none
language:
  en:
    callout-tip-title: "Your turn"
    callout-note-title: "Thinking outside the box"
    callout-warning-title: "Coding exercice"
    callout-important-title: "Key concept"
    callout-caution-title: "Pitfall"

preview:
  port: 3200
  browser: true
  watch-inputs: true
  navigate: true

book:
  title: Experimental design and statistical methods
  output-file: MATH80667A-EDSM
  author: Léo Belzile
  date: today
  chapters:
  - index.qmd
  - introduction.qmd
  - hypothesis_testing.qmd
  - completely_randomized_trials.qmd
  - contrasts_multipletesting.qmd
  - twoway.qmd
  - repeated.qmd
  - multiway.qmd
  - manova.qmd
  - ancova.qmd
  - power_effect.qmd
  - reproducibility_crisis.qmd
  - mixed.qmd
  - causal-inference.qmd
  - nonparametric.qmd
  - count.qmd
  - references.qmd
  site-url: https://lbelzile.github.io/math80667a/
  repo-url: https://github.com/lbelzile/math80667a/
  repo-branch: main
  repo-actions: [edit]
  search: true
  downloads: [pdf]
format:
  html:
    theme: custom.scss
    css: style.css
    reader-mode: true
    fig-align: center
    toc-location: right
    code-fold: false
    code-summary: "Code"
    code-overflow: wrap
    code-block-border-left: true
    code-copy: true
    engine: knitr
    default-image-extension: png
  pdf:
    documentclass: scrbook
    latex_documents:
       targetname: MATH80667A-EDSM.tex
    fontsize: 11pt
    fig-pos: "ht!"
    papersize: letter
    template-partials: 
      - before-body.tex
      - title.tex
    include-in-header: preamble.tex
    include-before-body: coverpage.tex
    pdf-engine: pdflatex
    citation-package: natbib
    keep-tex: true
    biblio-style: apalike2

